name: 'Upload changed/added files to S3'
description: 'Great tools for upload specific files'
inputs:
  files-added-to-sync:  # id of input
    description: 'all of the files changed/modified in a pull request'
    required: true
    default: 'None'
  files-modified-to-sync:  # id of input
    description: 'all of the files changed/modified in a pull request'
    required: true
    default: 'None'
  aws-s3-bucket:  # id of input
    description: 'all of the files changed/modified in a pull request'
    required: true
    default: 'None'
  aws-access-key-id:  # id of input
    description: 'AWS Key ID'
    required: true
    default: 'None'
  aws-secret-access-key:  # id of input
    description: 'AWS Secret'
    required: true
    default: 'None'
  aws-region:  # id of input
    description: 'Region'
    required: true
    default: 'None'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files-added-to-sync }}
    - ${{ inputs.files-modified-to-sync }}
    - ${{ inputs.aws-s3-bucket }}
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-region }}