name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  files-added-to-sync:  # id of input
    description: 'all of the files changed/modified in a pull request'
    required: true
    default: 'None'
  files-modified-to-sync:  # id of input
    description: 'all of the files changed/modified in a pull request'
    required: true
    default: 'None'
  files-added_modified-to-sync:  # id of input
    description: 'all of the files changed/modified in a pull request'
    required: true
    default: 'None'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files-added-to-sync }}
    - ${{ inputs.files-modified-to-sync }}
    - ${{ inputs.files-added_modified-to-sync }}