on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Git status files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          files-to-sync: ${{ steps.files.outputs.all }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"